apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2 # 실행할 Pod 수
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: leejeayoung/my-node-app:latest # Docker Hub 이미지
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred # Docker Hub 비밀
